const activities = [
  {
    id: 1,
    location: 'NOIRlab Headquarters',
    activity: 'Automóvil - diesel',
    amount: 1,
    month: 'Enero',
    valueHO2: 10.15,
    valueCH4: 0.0013679,
    valueN2O: 0.0000821,
  },
  {
    id: 2,
    location: 'NOIRlab Research Center',
    activity: 'Automóvil - diesel',
    amount: 1,
    month: 'Enero',
    valueHO2: 10.15,
    valueCH4: 0.0013679,
    valueN2O: 0.0000821,
  },
  {
    id: 3,
    location: 'NOIRlab Research Center',
    activity: 'Camioneta - Gasolina Comercial E10',
    amount: 1,
    month: 'Enero',
    valueHO2: 66778.409,
    valueCH4: 3,
    valueN2O: 3.2,
  },
  {
    id: 4,
    location: 'NOIRlab Research Center',
    activity: 'Camioneta - PCG',
    amount: 1,
    month: 'Enero',
    valueHO2: 1,
    valueCH4: 28,
    valueN2O: 265,
  },
  {
    id: 5,
    location: 'NOIRlab Research Center',
    activity: 'Consumo de Energía (Kwh) - Colombia',
    amount: 1,
    month: 'Enero',
    valueHO2: 0.126,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 6,
    location: 'NOIRlab Headquarters',
    activity: 'Motocicleta - diesel',
    amount: 1,
    month: 'Enero',
    valueHO2: 10.15,
    valueCH4: 0.0013679,
    valueN2O: 0.0000821,
  },
  {
    id: 7,
    location: 'NOIRlab Headquarters',
    activity: 'Motocicleta - diesel',
    amount: 1,
    month: 'Enero',
    valueHO2: 10.15,
    valueCH4: 0.0013679,
    valueN2O: 0.0000821,
  },
  {
    id: 8,
    location: 'NOIRlab Headquarters',
    activity: 'Motocicleta - diesel',
    amount: 1,
    month: 'Febrero',
    valueHO2: 10.15,
    valueCH4: 0.0013679,
    valueN2O: 0.0000821,
  },
  {
    id: 9,
    location: 'NOIRlab Research Center',
    activity: 'Motocicleta - diesel',
    amount: 1,
    month: 'Febrero',
    valueHO2: 10.15,
    valueCH4: 0.0013679,
    valueN2O: 0.0000821,
  },
  {
    id: 10,
    location: 'NOIRlab Research Center',
    activity: 'Motocicleta - diesel',
    amount: 1,
    month: 'Febrero',
    valueHO2: 10.15,
    valueCH4: 0.0013679,
    valueN2O: 0.0000821,
  },
  {
    id: 11,
    location: 'NOIRlab Research Center',
    activity: 'Consumo de Energía (Kwh) - Colombia',
    amount: 1,
    month: 'Febrero',
    valueHO2: 0.126,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 12,
    location: 'NOIRlab Headquarters',
    activity: 'Consumo de Energía (Kwh) - Colombia',
    amount: 1,
    month: 'Febrero',
    valueHO2: 0.126,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 13,
    location: 'NOIRlab Headquarters',
    activity: 'Motocicleta - diesel',
    amount: 1,
    month: 'Febrero',
    valueHO2: 10.15,
    valueCH4: 0.0013679,
    valueN2O: 0.0000821,
  },
  {
    id: 14,
    location: 'NOIRlab Headquarters',
    activity: 'Camioneta - PCG',
    amount: 1,
    month: 'Febrero',
    valueHO2: 1,
    valueCH4: 28,
    valueN2O: 265,
  },
  {
    id: 15,
    location: 'NOIRlab Observatory',
    activity: 'Camioneta - PCG',
    amount: 1,
    month: 'Febrero',
    valueHO2: 1,
    valueCH4: 28,
    valueN2O: 265,
  },
  {
    id: 16,
    location: 'NOIRlab Research Center',
    activity: 'Camioneta - PCG',
    amount: 1,
    month: 'Febrero',
    valueHO2: 1,
    valueCH4: 28,
    valueN2O: 265,
  },
  {
    id: 17,
    location: 'VLT Telescope',
    activity: 'Camioneta - PCG',
    amount: 1,
    month: 'Febrero',
    valueHO2: 1,
    valueCH4: 28,
    valueN2O: 265,
  },
  {
    id: 18,
    location: 'NOIRlab Observatory',
    activity: 'Camioneta - PCG',
    amount: 1,
    month: 'Febrero',
    valueHO2: 1,
    valueCH4: 28,
    valueN2O: 265,
  },
  {
    id: 19,
    location: 'NOIRlab Observatory',
    activity: 'Camioneta - PCG',
    amount: 1,
    month: 'Marzo',
    valueHO2: 1,
    valueCH4: 28,
    valueN2O: 265,
  },
  {
    id: 20,
    location: 'NOIRlab Observatory',
    activity: 'Consumo de Energía (Kwh) - Estados Unidos',
    amount: 1,
    month: 'Marzo',
    valueHO2: 2.88,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 21,
    location: 'NOIRlab Observatory',
    activity: 'Consumo de Energía (Kwh) - Países Bajos',
    amount: 1,
    month: 'Marzo',
    valueHO2: 0.533,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 22,
    location: 'NOIRlab Research Center',
    activity: 'Consumo de Energía (Kwh) - Países Bajos',
    amount: 1,
    month: 'Marzo',
    valueHO2: 0.533,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 23,
    location: 'NOIRlab Research Center',
    activity: 'Consumo de Energía (Kwh) - Colombia',
    amount: 1,
    month: 'Marzo',
    valueHO2: 0.126,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 24,
    location: 'NOIRlab Research Center',
    activity: 'Consumo de Energía (Kwh) - Colombia',
    amount: 1,
    month: 'Marzo',
    valueHO2: 0.126,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 25,
    location: 'NOIRlab Research Center',
    activity: 'Consumo de Energía (Kwh) - Colombia',
    amount: 1,
    month: 'Marzo',
    valueHO2: 0.126,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 26,
    location: 'NOIRlab Research Center',
    activity: 'Consumo de Energía (Kwh) - Colombia',
    amount: 1,
    month: 'Abril',
    valueHO2: 0.126,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 27,
    location: 'NOIRlab Research Center',
    activity: 'Consumo de Energía (Kwh) - Colombia',
    amount: 1,
    month: 'Abril',
    valueHO2: 0.126,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 28,
    location: 'NOIRlab Research Center',
    activity: 'Consumo de Energía (Kwh) - Colombia',
    amount: 1,
    month: 'Abril',
    valueHO2: 0.126,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 29,
    location: 'NOIRlab Research Center',
    activity: 'Automóvil - Gasolina Comercial E10',
    amount: 1,
    month: 'Enero',
    valueHO2: 66778.409,
    valueCH4: 3,
    valueN2O: 3.2,
  },
  {
    id: 30,
    location: 'NOIRlab Research Center',
    activity: 'Consumo de Energía (Kwh) - Colombia',
    amount: 1,
    month: 'Abril',
    valueHO2: 0.126,
    valueCH4: 0,
    valueN2O: 0,
  },
  {
    id: 31,
    location: 'NOIRlab Research Center',
    activity: 'Consumo de Energía (Kwh) - Colombia',
    amount: 1,
    month: 'Abril',
    valueHO2: 0.126,
    valueCH4: 0,
    valueN2O: 0,
  },
]

export default activities
