const company = {
  name: 'NOIRLab',
  contact: 'Jon Doe',
  logo: 'https://noirlab.edu/public/media/archives/logos/svg/logo006.svg',
  address: '950 N. Cherry Ave. Tucson, AZ 85719, USA',
  country: 'USA',
  postalCode: 'AZ 85719',
  estate: 'Tucson',
  phone: 'Tel: +1 520 318 8000',
  email: 'info@noirlab.edu',
  url: 'https://noirlab.edu/public',
  membership: {
    locationLimit: 5,
    workersLimit: 50,
  },
  locations: [
    {
      id: 1,
      name: 'NOIRlab Headquarters',
      address: 'Space',
      phone: '555-987-6543',
      email: 'hq@noirlab.com',
      employees: 135,
      status: 'very-good',
    },
    {
      id: 2,
      name: 'NOIRlab Research Center',
      address: '789 Oak Avenue',
      phone: '555-456-7890',
      email: 'research@noirlab.com',
      employees: 71,
      status: 'fair',
    },
    {
      id: 3,
      name: 'NOIRlab Observatory',
      address: '321 Pine Road',
      phone: '555-789-0123',
      email: 'observatory@noirlab.com',
      employees: 51,
      status: 'bad',
    },
    {
      id: 4,
      name: 'ALMA Telescope',
      address: 'Atacama Desert, Chile',
      phone: '555-456-7890',
      email: 'ctio@noirlab.com',
      employees: 10,
      status: 'very-bad',
    },
    {
      id: 5,
      name: 'NOIRlab Research Center',
      address: '789 Oak Avenue',
      phone: '555-456-7890',
      email: 'research@noirlab.com',
      employees: 150,
      status: 'good',
    },
    {
      id: 6,
      name: 'VLT Telescope',
      address: 'Paranal Observatory, Chile',
      phone: '555-456-7890',
      email: 'cpachon@noirlab.com',
      employees: 9,
      status: 'very-good',
    },

  ],
}

export default company
