const emissionFactors = [
  {
    id: '1',
    name: 'Camioneta - diesel',
    description: 'FACTOR DE EMISION POR TIPO DE MEDIO DE TRANSPORTE (Cuando no conoce el tipo de combustible que utiliza, mas que todo es servicio público)',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 10.15,
      CH4: 0.0013679,
      N2O: 0.0000821,
    },
  },
  {
    id: '2',
    name: 'Automóvil - diesel',
    description: '',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 10.15,
      CH4: 0.0013679,
      N2O: 0.0000821,
    },
  },
  {
    id: '3',
    name: 'Motocicleta - diesel',
    description: '',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 10.15,
      CH4: 0.0013679,
      N2O: 0.0000821,
    },
  },
  {
    id: '4',
    name: 'Buseta - diesel',
    description: '',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 10.15,
      CH4: 0.0013679,
      N2O: 0.0000821,
    },
  },
  {
    id: '5',
    name: 'Camioneta - Gasolina Comercial E10',
    description: 'FACTOR DE EMISION POR TIPO DE MEDIO DE TRANSPORTE (Cuando no conoce el tipo de combustible que utiliza, mas que todo es servicio público)',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 66778.409,
      CH4: 3.0,
      N2O: 3.2,
      SO2: 10.9589,
    },
  },
  {
    id: '6',
    name: 'Automóvil - Gasolina Comercial E10',
    description: '',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 66778.409,
      CH4: 3.0,
      N2O: 3.2,
      SO2: 10.9589,
    },
  },
  {
    id: '7',
    name: 'Motocicleta - Gasolina Comercial E10',
    description: '',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 66778.409,
      CH4: 3.0,
      N2O: 3.2,
      SO2: 10.9589,
    },
  },
  {
    id: '8',
    name: 'Buseta - Gasolina Comercial E10',
    description: '',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 66778.409,
      CH4: 3.0,
      N2O: 3.2,
      SO2: 10.9589,
    },
  },
  {
    id: '9',
    name: 'Camioneta - PCG',
    description: 'FACTOR DE EMISION POR TIPO DE MEDIO DE TRANSPORTE (Cuando no conoce el tipo de combustible que utiliza, mas que todo es servicio público)',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 1.0,
      CH4: 28.0,
      N2O: 265,
    },
  },
  {
    id: '10 - PCG',
    name: 'Automóvil - PCG',
    description: '',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 1.0,
      CH4: 28.0,
      N2O: 265,
    },
  },
  {
    id: '11',
    name: 'Motocicleta - PCG',
    description: '',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 1.0,
      CH4: 28.0,
      N2O: 265,
    },
  },
  {
    id: '12',
    name: 'Buseta - PCG',
    description: '',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 1.0,
      CH4: 28.0,
      N2O: 265,
    },
  },
  {
    id: '13',
    name: 'Bicicleta',
    description: '',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 0.0,
      CH4: 0.0,
      N2O: 0.0,
    },
  },
  {
    id: '14',
    name: 'Caminando',
    description: '',
    category: 'Transporte',
    emission_factor: {
      quantity: 1,
      CO2: 0.0,
      CH4: 0.0,
      N2O: 0.0,
    },
  },
  {
    id: '15',
    name: 'Consumo de Energía (Kwh) - Alemania',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '16',
    name: 'Consumo de Energía (Kwh) - Australia',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '17',
    name: 'Consumo de Energía (Kwh) - Austria',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.55,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '18',
    name: 'Consumo de Energía (Kwh) - Bélgica',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.189,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '19',
    name: 'Consumo de Energía (Kwh) - Brasil',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '20',
    name: 'Consumo de Energía (Kwh) - Colombia',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.126,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '21',
    name: 'Consumo de Energía (Kwh) - Ecuador',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '22',
    name: 'Consumo de Energía (Kwh) - España',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '23',
    name: 'Consumo de Energía (Kwh) - Estados Unidos',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 2.88,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '24',
    name: 'Consumo de Energía (Kwh) - Finlandia',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.301,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '25',
    name: 'Consumo de Energía (Kwh) - Francia',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.05,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '26',
    name: 'Consumo de Energía (Kwh) - Grecia',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.695,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '27',
    name: 'Consumo de Energía (Kwh) - India',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '28',
    name: 'Consumo de Energía (Kwh) - Indonesia',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '29',
    name: 'Consumo de Energía (Kwh) - Israel',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '30',
    name: 'Consumo de Energía (Kwh) - Italia',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '31',
    name: 'Consumo de Energía (Kwh) - México',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '32',
    name: 'Consumo de Energía (Kwh) - Países Bajos',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.533,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '33',
    name: 'Consumo de Energía (Kwh) - Polonia',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.904,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '34',
    name: 'Consumo de Energía (Kwh) - Portugal',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.315,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '35',
    name: 'Consumo de Energía (Kwh) - Reino Unido',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.38,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '36',
    name: 'Consumo de Energía (Kwh) - Rusia',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '37',
    name: 'Consumo de Energía (Kwh) - Suiza',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.034,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  {
    id: '38',
    name: 'Consumo de Energía (Kwh) - Turquía',
    description: 'Consume kwh (mes) x (factor de emisión) x (PCC CO2)',
    category: 'Energía',
    emission_factor: {
      quantity: 1.0,
      CO2: 0.2,
      CH4: 0.0,
      N2O: 0.0,
      PCG: 1,
    },
  },
  [
    {
      id: '39',
      name: 'No adecuada clasificación de residuos',
      category: 'Residuos',
      description: '',
      emission_factor: {
        quantity: 1,
        CO2: 0,
        CH4: 29.687,
      },
    },
    {
      id: '40',
      name: 'Residuos No Aprovechables',
      category: 'Residuos',
      description: '',
      emission_factor: {
        quantity: 1,
        CO2: 0,
        CH4: 0.1,
      },
    },
    {
      id: '41',
      name: 'Residuos Aprovechables',
      category: 'Residuos',
      description: '',
      emission_factor: {
        quantity: 1,
        CO2: 0,
        CH4: 0.0012,
      },
    },
    {
      id: '42',
      name: 'Residuos Organicos Aprovechables',
      category: 'Residuos',
      description: '',
      emission_factor: {
        quantity: 1,
        CO2: 0,
        CH4: 0,
      },
    },
    {
      id: '43',
      name: 'No adecuada clasificación de residuos - PCG',
      category: 'Residuos',
      description: '',
      emission_factor: {
        quantity: 1,
        CO2: 1,
        CH4: 28,
      },
    },
    {
      id: '44',
      name: 'Residuos No Aprovechables - PCG',
      category: 'Residuos',
      description: '',
      emission_factor: {
        quantity: 1,
        CO2: 1,
        CH4: 28,
      },
    },
    {
      id: '45',
      name: 'Residuos Aprovechables - PCG',
      category: 'Residuos',
      description: '',
      emission_factor: {
        quantity: 1,
        CO2: 1,
        CH4: 28,
      },
    },
    {
      id: '46',
      name: 'Residuos Organicos Aprovechables - PCG',
      category: 'Residuos',
      description: '',
      emission_factor: {
        quantity: 1,
        CO2: 0,
        CH4: 0,
      },
    },
  ],
]

export default emissionFactors
