/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/button.vue')['default']
    CheckBox: typeof import('./components/checkBox.vue')['default']
    Icon: typeof import('./components/icon.vue')['default']
    Logo: typeof import('./components/logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignSocial: typeof import('./components/signSocial.vue')['default']
    Social: typeof import('./components/social.vue')['default']
    TextField: typeof import('./components/textField.vue')['default']
  }
}
