/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonAuth: typeof import('./components/buttonAuth.vue')['default']
    CheckBox: typeof import('./components/checkBox.vue')['default']
    CheckBoxAuth: typeof import('./components/checkBoxAuth.vue')['default']
    Header: typeof import('./components/header/index.vue')['default']
    Icon: typeof import('./components/icon.vue')['default']
    Language: typeof import('./components/header/navTools/language.vue')['default']
    Logo: typeof import('./components/logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInSocial: typeof import('./components/signInSocial.vue')['default']
    SwitchDark: typeof import('./components/header/navTools/switchDark.vue')['default']
    TextField: typeof import('./components/textField.vue')['default']
    TextFieldAuth: typeof import('./components/textFieldAuth.vue')['default']
  }
}
